### ISSUE TITLE
Expose all bindings in a kernel as GetBindings method

### ISSUE THREAD

**Issue by hach-que** [ninject/Ninject#104]
We currently have an extension method:

```
        /// <summary>
        /// Get all of the types bound in the kernel.
        /// </summary>
        public static Type[] GetBindings(this IKernel kernel)
        {
            return ((Multimap<Type, IBinding>)typeof(KernelBase)
                .GetField("bindings", BindingFlags.NonPublic | BindingFlags.Instance)
                .GetValue(kernel)).Select(x => x.Key).ToArray();
        }
```

We use this in unit tests to verify that all bindings in a kernel are correctly resolved and that there are no missing dependencies.  It would be great if this functionality was exposed on the standard kernel so we don't need to resort to reflection to access a private field (which is liable to break in future versions of Ninject).

**Comment by jupaol** [comment]
It would be even better if Ninject exposed a method to verify the configuration is valid, something like the `AssertConfigurationIsValid` method in StructureMap http://docs.structuremap.net/QuickStart.htm

**Comment by Dashue** [comment]
Wow still no action on this? 
I cannot count the times this would've prevented issues in production.

Any workarounds or plans to introduce this?

**Comment by scott-xu** [comment]
A PR is welcome.

**Comment by scott-xu** [comment]
The plan is to add "Verify()" to the kernel.

**Comment by pimterry** [comment]
Is there an issue to track that? I'd find a `verify()` method useful, and I'd potentially be interested in helping put it together.

**Comment by jamiebarrow** [comment]
I too would like to verify that registered bindings can result in all resolutions to be successful, without having to write full system tests - not always possible to do this on legacy systems. I second (or well, third) the vote to have an IKernel.Verify() method, that would attempt to verify that all registrations can be resolved without missing dependencies.

**Comment by hach-que** [comment]
I don't think it's likely this feature will ever end up in Ninject based on what's been discussed above.  In the end I wrote my [own dependency injection system](https://github.com/RedpointGames/Protoinject) which supports validation.
