### ISSUE TITLE
Deadlock on Context.Resolve()

### ISSUE THREAD

**Issue by cmenzi** [ninject/Ninject#127]
Since we updated to 3.2.0.0 we get a deadlock while resolving an instance. The instance is resolved in a seperate thread.

I had the idea, it must be related to this commit: https://github.com/ninject/ninject/commit/cd508e9564e1b21f2ac0d48ffe42564328da42a6

I've downloaded the source and changed to `lock` back to the `Binding`

```
lock(Binding)
{
}
```

And now it works!

**Comment by drieseng** [comment]
No feedback.
