### ISSUE TITLE
After upgrading to Ninject 3.2.2 we get a Cyclic Dependancy Exception

### ISSUE THREAD

**Issue by andersosthus** [ninject/Ninject#131]
Hi,

We've been using Ninject 3.2.0 since it was released without issues. Now, when upgrading to 3.2.2, we get an exception in Bootstrapper.Initialize(CreateKernel):

```
Error activating ModelValidatorProvider using binding from ModelValidatorProvider to NinjectDefaultModelValidatorProvider
A cyclical dependency was detected between the constructors of two services.

Activation path:
  3) Injection of dependency ModelValidatorProvider into parameter defaultModelValidatorProviders of constructor of type DefaultModelValidatorProviders
  2) Injection of dependency DefaultModelValidatorProviders into parameter defaultModelValidatorProviders of constructor of type NinjectDefaultModelValidatorProvider
  1) Request for ModelValidatorProvider

Suggestions:
  1) Ensure that you have not declared a dependency for ModelValidatorProvider on any implementations of the service.
  2) Consider combining the services into a single one to remove the cycle.
  3) Use property injection instead of constructor injection, and implement IInitializable
     if you need initialization logic to be run after property values have been injected.
```

There has been no changes to the bindings, so either we've had a Cyclic dependency all the time, or a bug has snuck in somewhere.

The Ninject packages we have installed are:

```
Ninject 3.2.2.0
Ninject.Extensions.Conventions 3.2.0.0
Ninject.MVC3 3.2.1.0
Ninject.Web.Common 3.2.1.0
Ninject.Web.Common.WebHost 3.2.1.0
Ninject.Web.WebApi 3.2.1.0
```

The project is a MVC5 with WebAPI 2.1 project.

Have you seen this before?

**Comment by arindamdat** [comment]
The cyclic dependency is between the classes "NinjectDefaultModelValidatorProvider" and "DefaultModelValidatorProviders".Simply add a binding for "DefaultModelValidatorProviders" on your startup like below:
<pre>
_kernel.Bind&lt;DefaultModelValidatorProviders&gt;().ToConstant(new DefaultModelValidatorProviders(config.Services.GetServices(typeof (ModelValidatorProvider)).Cast&lt;ModelValidatorProvider&gt;()));
</pre>

**Comment by bananabags** [comment]
I had the same problem. When I added:
`_kernel.Bind<DefaultModelValidatorProviders>().ToConstant(new DefaultModelValidatorProviders(config.Services.GetServices(typeof (ModelValidatorProvider)).Cast<ModelValidatorProvider>()));` 
I got the next problem with DefaultFilters provider, if you had the same problem, just add:
`kernel.Bind<DefaultFilterProviders>().ToConstant(new DefaultFilterProviders(new[] { new NinjectFilterProvider(kernel) }.AsEnumerable()));`. I'm not sure that is the best solving but it works for me. Thanks.

**Comment by testfirstcoder** [comment]
@bananabags After adding the code needed for DefaultFilters got following error:
Error activating DefaultFilterProviders
More than one matching bindings are available.
Matching bindings:
  1) binding from DefaultFilterProviders to constant value
  2) binding from DefaultFilterProviders to constant value
Activation path:
  2) Injection of dependency DefaultFilterProviders into parameter filterProviders of constructor of type DefaultFilterProvider
  1) Request for IFilterProvider

Suggestions:
  1) Ensure that you have defined a binding for DefaultFilterProviders only once.

Any ideas/suggestions?
