### ISSUE TITLE
InRequestScope is failing to dispose objects

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [ninject/Ninject#132]
based on http://www.mistergoodcat.com/post/How-Ninject-inadvertently-made-the-case-for-SOLID

I was able to reproduce the issue with the Ninject.MVC5 package as well.

**Comment by johnkors** [comment]
Upgrading from `3.2.0` -> `3.2.2` fixed this issue for us. Thanks. Is it possible to unlist that bad package in NuGet?

**Comment by BrunoJuchli** [comment]
https://docs.nuget.org/create/deleting-packages
should be...

**Comment by edaloicaro18** [comment]
Upgrading all the Ninject packages to their latest versions fixed this issue for me as well
