### ISSUE TITLE
Windows Universal Apps

### ISSUE THREAD

**Issue by iJoyCode** [ninject/Ninject#135]
Hello, Do you plan to adapt Ninject for Windows Universal Apps?

**Comment by onovotny** [comment]
Windows Universal apps, and Xamarin ones, are supported in my Ninject fork, Portable.Ninject: https://github.com/onovotny/ninject. The nuget package is Portable.Ninject

**Comment by scott-xu** [comment]
@iJoyCode implemented

**Comment by ckuhn203** [comment]
Has this been mainlined yet @scott-xu?
