### ISSUE TITLE
After upgrade to Ninject 3.2.2 I get A cyclical dependency

### ISSUE THREAD

**Issue by VansFannel** [ninject/Ninject#149]
Like this issue, https://github.com/ninject/ninject/issues/131, I get a cyclical dependency after update Ninject to version 3.2.2.

I have asked this question, http://stackoverflow.com/questions/26312231/ninjectdependencyresolver-fails-binding-modelvalidatorprovider, on SO.

I don't know how to solve this issue. Any idea?

**Comment by l0nley** [comment]
Still have it with ninject webapi 3.2.4 and selfhosted webapi. does it fixed?

**Comment by BrunoJuchli** [comment]
@l0nley did you follow the steps outlined [here](http://stackoverflow.com/a/27399451/684096)?

From which version did you migrate to 3.2.4?

**Comment by l0nley** [comment]
_kernel.Bind<DefaultModelValidatorProviders>().ToConstant(new DefaultModelValidatorProviders(config.Services.GetServices(typeof (ModelValidatorProvider)).Cast<ModelValidatorProvider>()));
works for me. But i totally dont understand why i should do so nasty things to get ninject up and running. I not migrated from any previous version- just installed the package and get this error, when replace default DR with NinjectDepedencyResolver.
