### ISSUE TITLE
Ninject.Extensions.Wcf should have Ninject.Web as a dependency

### ISSUE THREAD

**Issue by ryanlangton** [ninject/Ninject#156]
The Ninject.Extensions.Wcf needs Ninject.Web as a dependency.  I've spent a lot of time troubleshooting Ninject failing to initialize (with injection) a Wcf Service, and this is because it still needed the Ninject.Web bootstrapping.  I've seen other solutions suggested to use Global.asax inheriting from a NinjectHttpApplication, but this does not work.  Ultimately this stackoverflow post shows the problem and the solution (see the solution posted by ParaSwarm).  It would save a lot of headaches to have Ninject.Web download automatically with Ninject.Extensions.Wcf.

http://stackoverflow.com/questions/17193562/wcf-ninject-default-parameter-less-constructor

**Comment by scott-xu** [comment]
Please use this nuget package: Ninject.Extensions.Wcf.WebHost
