### ISSUE TITLE
Please add PDB file for Ninject

### ISSUE THREAD

**Issue by mc0re** [ninject/Ninject#160]
In order to understand and debug Ninject, a PDB file is needed along with sources. Please, add it to distribution.

**Comment by mc0re** [comment]
I've read that pushing PDB file to symbolsource.org is also an option.

**Comment by scott-xu** [comment]
You got it. It's already being pushed.

**Comment by mc0re** [comment]
I can't see it there, nor can VS 2013!

**Comment by mc0re** [comment]
But VS 2013 cannot see it, then...
I set symbol server to http://symbolsource.org to no avail.
 
Date: Thu, 8 Jan 2015 01:37:14 -0800

**Comment by BrunoJuchli** [comment]
Could it be that the pdb file is from same source revision but from a different build?
As far as i remember: If you do a rebuild the resulting pdb file does not match the dll file anymore - even if there were no source file changes at all.

**Comment by mc0re** [comment]
I do not build Ninject, I only use it - got via NuGet. So I cannot build PDB files.
 
By the way, you're right, PDB files can differ for the same source files, because recompilation can take a slightly different route.
 
Date: Thu, 8 Jan 2015 07:49:18 -0800

**Comment by scott-xu** [comment]
Please make sure your link is correct: http://srv.symbolsource.org/pdb/Public
