### ISSUE TITLE
Ninject.org down

### ISSUE THREAD

**Issue by BrunoJuchli** [ninject/Ninject#161]
Ninject.org is currently down. Will it be back?
(Also see http://stackoverflow.com/questions/27851499/ninject-ioc-project-website)

**Comment by scott-xu** [comment]
@remogloor @danielmarbach , any updates?

**Comment by danielmarbach** [comment]
Repo and cname entry is still correct. Could be an issue of github nameserver or domain registrar. I have no idea who owns the domain and has paid for it

**Comment by idavis** [comment]
The DNS just had to be updated. It is fixed now.
