### ISSUE TITLE
Deadlock with Ninject 3.2.2 (with code sample)

### ISSUE THREAD

**Issue by lsoft** [ninject/Ninject#162]
I have faced with deadlock in scenario where there are more than one container. I think it's just a misusing from my side and I'm going to simplify my binding architecture.
Nevertheless, I would be happy if someone shed light about the reasons of the deadlock. Also, I guess it would be helpful for Ninject users to have a way to set a lock timeout.

VS 2012 solution can be downloaded from my dropbox https://www.dropbox.com/s/9q9r16xxc56v63f/NInject%20deadlock%20example.zip?dl=0
The sample isn't a small enough to post the code in this issue, sorry for that.

Thanks!

**Comment by scott-xu** [comment]
InSingletonScope will lock the kernel when Resolve. In your sample, thread1 will lock kernel1 and then try to lock kernel2, thread2 will lock kernel2 and then try to lock kernel1. That's the reason of your dead lock.

**Comment by lsoft** [comment]
Got it.  What's about a way to define a finite lock timeout? Is it helpful? If not, should I close this issue as "not a bug"?

**Comment by scott-xu** [comment]
I don't think it's a bug. It is not recommended that more than one kernel is introduced in one application.

**Comment by lsoft** [comment]
Ok. Thanks for reply.
