### ISSUE TITLE
Incomplete implementation ReaderWriterLock for Silverlight and Compact Framework

### ISSUE THREAD

**Issue by lsoft** [ninject/Ninject#163]
A lock must be acquired and released in the same thread. Looks like ReaderWriterLock does not check this point.

Pseudo code:
var rwl = new ReaderWriterLock();

var thread1 =
   rwl.AcquireReaderLock(1000);
   exit;

var thread2 =
   sleep for some time;
   rwl.ReleaseReaderLock();
   exit;

thread1.start();
thread2.start();

works without errors.

I think it's has lowest priority because both platforms are obsolete.
But it would be fine to see an efficient and complete implementation ReaderWriterLock(Slim) for Compact Framework.

**Comment by scott-xu** [comment]
Both platforms are not supported now.
