### ISSUE TITLE
InRequestScope is ignored for async WCF calls

### ISSUE THREAD

**Issue by jowensboggs** [ninject/Ninject#164]
When using in an async WCF call, InRequestScope is ignored after a method call is awaited, and the injected objects are not disposed.

**Comment by jowensboggs** [comment]
Looks like NinjectWcfHttpApplicationPlugin.GetRequestScope is returning null because OperationContext.Current has not been set on the active thread.

**Comment by scott-xu** [comment]
Can you please send a sample to me?

**Comment by jowensboggs** [comment]
Certainly,
Where should I put it?  I currently have it as a clone of the NInject + Common + WCF + Demo all in one solution from February, with an additional WCF project demo project. Zipped, It’s about 44K?

**Comment by scott-xu** [comment]
@jowensboggs scott-xu at msn.com

**Comment by scott-xu** [comment]
@jowensboggs  It works in my case.

**Comment by jowensboggs** [comment]
Yes, when I tried to replicate before forwarding the sample code on, I could not… meant to dig in to see if I changed something, or to better get a handle on what I was doing originally, but … no luck…

Guess I can’t replicate….
