### ISSUE TITLE
Would a convention that private ctor > InSingletonScope make sense?

### ISSUE THREAD

**Issue by JohanLarsson** [ninject/Ninject#173]
The idea is:
```
    [Fact]
    public void ResolvePrivateCtor()
    {
        var kernel = new StandardKernel();
        var first = kernel.Get<WithPrivateCtor>();
        var second = kernel.Get<WithPrivateCtor>();
        Assert.Same(first, second); // Singleton
    }

    public class WithPrivateCtor
    {
        private WithPrivateCtor()
        {
        }
    }

ie private ctor would result in:
    kernel.Bind<WithPrivateCtor>()
          .ToSelf()
          .InSingletonScope();
```
Asking here before writing any code.

**Comment by BrunoJuchli** [comment]
Seems strange to me. It's something that really should not be on by default. There should only be a few conventions and those should be easy to remember and identify.
I don't think this applies here.

While it's clear that if you want to implement the singleton pattern in a classic way you'd have a private ctor, it's unclear why a private ctor necessarily leads to a singleton (there's other use cases for private ctors).

**Comment by JohanLarsson** [comment]
I agree it should not be the default. InjectNonPublic or a new flag ResolvePrivateCostructors could make sense.

Chaning ctor to private is very little code and closes the door for newing it up.
We have ~1000 lines of setup code and maintaining it is not much fun. Also I have spent many hours tracking down bugs caused by things that should have been singleton were not.
