### ISSUE TITLE
InvalidProgramException due to invalid IL being generated

### ISSUE THREAD

**Issue by mattwarren** [ninject/Ninject#175]
If you setup a binding like so:
``` csharp
Bind<Func<ILogging>>().ToMethod(ctx => () => new MockLogging());
```

In [DynamicMethodInjectorFactory it creates](https://github.com/ninject/Ninject/blob/master/src/Ninject/Injection/DynamicMethodInjectorFactory.cs#L32) some IL for the `Func<ILogging>` constructor (`ctor(System.Object, IntPtr)`) that looks like this:
```
ldarg.0
ldc.i4, 0
ldelem.ref
castclass, System.Object
ldarg.0
ldc.i4, 1
ldelem.ref
unbox.any, System.IntPtr
newobj, Void .ctor(System.Object, IntPtr) System.Func`1[ILogging]
ret
```

The problem is that you can't use this method when dealing with an `IntPtr`, because it's really a pointer to a method. To do this you have to emit the IL like so:
```
il.Emit(OpCodes.Ldftn, methodInfo);
il.Emit(OpCodes.Newobj, constructorInfo);
```
So you have to use the [Ldftn OpCode](https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.ldftn%28v=vs.110%29.aspx) and work directly with a [MethodInfo](https://msdn.microsoft.com/en-us/library/system.reflection.methodinfo%28v=vs.110%29.aspx). See [this SO answer](http://stackoverflow.com/questions/3915827/get-ldftn-function-pointer-in-c-sharp/3915967#3915967) for more info. 

So normally this isn't a problem, because the IL that is compiled into a delegate doesn't *seem* to get executed when you use a binding as shown above. It uses the [`CallbackProvider`](https://github.com/ninject/Ninject/blob/master/src/Ninject/Activation/Providers/CallbackProvider.cs) that doesn't use the [`ConstructorInjector`](https://github.com/ninject/Ninject/blob/master/src/Ninject/Injection/ConstructorInjector.cs) (like the [`StandardProvider`](https://github.com/ninject/Ninject/blob/master/src/Ninject/Activation/Providers/StandardProvider.cs) does). If the compiled delegate was ever executed, then it would throw an `InvalidProgramException`.

**But** if Ninject is used in conjunction with any product that uses the [.NET profiling API](https://msdn.microsoft.com/en-us/library/bb384493%28v=vs.110%29.aspx), this exception is instead thrown when the delegate is [*compiled*](https://github.com/ninject/Ninject/blob/d1660fb7f4816b2fae2c42dd662350d4e223ef60/src/Ninject/Injection/DynamicMethodInjectorFactory.cs#L57), which is a problem. This includes profilers, code coverage tools and production monitoring systems (the last of which the company I work for makes).

**Questions**
1. Am I right in thinking that when using a `Binding` as shown at the top of this post, the `ConstructorInjector` is never used? (I can't see how, but I just want to check this)
2. Is it possible to get a fix in Ninject, so that the invalid IL isn't generated (especially if it turns out to be redundant, based on the answer to 1).

I know that normally the solution to this is to use code like this:
``` csharp
INinjectSettings settings = new NinjectSettings
{
    UseReflectionBasedInjection = true,     // disable code generation for partial trust
    InjectNonPublic = false,                // disable private reflection for partial trust
    InjectParentPrivateProperties = false,  // reduce magic
    LoadExtensions = false                  // reduce magic
};
```
But the problem with this is that `UseReflectionBasedInjection` is slower, so there's a performance hit for all the injection done by Ninject.

BTW this problem *could* be the same as [this issue](https://groups.google.com/d/msg/ninject/M64UuvBoLUU/fQr8OhwOa_MJ) and [this one](http://stackoverflow.com/questions/5772860/exception-when-using-ninject)

**Comment by mattwarren** [comment]
Just to add, if you want to verify that the invalid IL throws the exception when executed, you can change the [code here](https://github.com/ninject/Ninject/blob/d1660fb7f4816b2fae2c42dd662350d4e223ef60/src/Ninject/Injection/DynamicMethodInjectorFactory.cs#L57) to

``` csharp
try
{
    var ctorDelegate = (ConstructorInjector)dynamicMethod.CreateDelegate(typeof(ConstructorInjector));

    if (constructor.DeclaringType.Namespace == "System"
        && constructor.DeclaringType.Name.StartsWith("Func`"))
    {
        MethodInfo testMethod = new methodof<Action>(Console.WriteLine);
        ctorDelegate(null, testMethod.MethodHandle.GetFunctionPointer());
    }

    return ctorDelegate;
}
catch (InvalidProgramException invalidProgramException)
{
    Console.WriteLine(invalidProgramException);
}

// Original code
//return (ConstructorInjector) dynamicMethod.CreateDelegate(typeof(ConstructorInjector));
```

You'll also need the `methodof` helper class, for that see [this gist](https://gist.github.com/mattwarren/efbb18cfa8bbae901a16)

**Comment by mattwarren** [comment]
Just to add, if you want to verify that the invalid IL throws an `InvalidProgramException` when executed, you can change the [code here](https://github.com/ninject/Ninject/blob/d1660fb7f4816b2fae2c42dd662350d4e223ef60/src/Ninject/Injection/DynamicMethodInjectorFactory.cs#L57) to

``` csharp
try
{
    var ctorDelegate = (ConstructorInjector)dynamicMethod.CreateDelegate(
								typeof(ConstructorInjector));

    if (constructor.DeclaringType.Namespace == "System"
        && constructor.DeclaringType.Name.StartsWith("Func`"))
    {
        MethodInfo testMethod = new methodof<Action>(Console.WriteLine);
        ctorDelegate(null, testMethod.MethodHandle.GetFunctionPointer());
    }

    return ctorDelegate;
}
catch (InvalidProgramException invalidProgramException)
{
    Console.WriteLine(invalidProgramException);
}

// Original code
//return (ConstructorInjector) dynamicMethod.CreateDelegate(typeof(ConstructorInjector));
```

You'll also need the `methodof` helper class, for that see [this gist](https://gist.github.com/mattwarren/efbb18cfa8bbae901a16).

**Comment by mattwarren** [comment]
Would it help if I put together a pull-request to show a possible fix for this issue?

If so, could someone please clarify something for me?

> Am I right in thinking that when using a Binding like so `Bind<Func<ILogging>>().ToMethod(ctx => () => new MockLogging());`, the `ConstructorInjector` is never used? I.e. the [IL emitted](https://github.com/ninject/Ninject/blob/master/src/Ninject/Injection/DynamicMethodInjectorFactory.cs#L32-59) is never actually executed? 

From what I can tell from looking around the Ninject code, this is because [CallbackProvider](https://github.com/ninject/Ninject/blob/master/src/Ninject/Activation/Providers/CallbackProvider.cs) is used instead of a [StandardProvider](https://github.com/ninject/Ninject/blob/master/src/Ninject/Activation/Providers/StandardProvider.cs) (which would've used the `ConstructorInjector`)

**Comment by idavis** [comment]
Can you write an integration test that show's this behavior? In the meantime, would it be easier to just have an interface as a provider rather than injecting a Func?

**Comment by mattwarren** [comment]
> Can you write an integration test that show's this behaviour?

Yeah no problem, I'll put something together.

> In the meantime, would it be easier to just have an interface as a provider rather than injecting a Func?

If you have a binding like this:
``` csharp
Bind<ILogging>().To<MockLogging>();
```
I can absolutely see the point of creating a `ConstructorInjector` in [`DynamicMethodInjectorFactory`](https://github.com/ninject/Ninject/blob/master/src/Ninject/Injection/DynamicMethodInjectorFactory.cs#L32), because `MockLogging` might have a ctor that takes other dependancies, for instance if could be `public MockLogging(IFileWriter fileWriter)`. So you'd want to be able to create a `MockLogger` (to satisfy the `ILogging` dependency) and at the same time pass in the `IFileWriter` dependency.

But when you have a binding like this:
``` csharp
Bind<Func<ILogging>>().ToMethod(ctx => () => new MockLogging());
```

I'm a bit confused as to why Ninject tries to create a `ConstructorInjector` for the `Func<ILogging>` ctor (`private void .ctor(System.Object, System.IntPtr)`). In what scenario would Ninject need to create a `Func<ILogging>` object in that way? It's bound via `ToMethod()`, so the Func `ctx => () => new MockLogging()` is called to create the `ILogging` dependency. 

I can't think of a scenario where Ninject needs to create a `Func<ILogging>` object, but maybe I'm missing something?

**Comment by mattwarren** [comment]
I've added a code sample, with a failing test to demonstrate the issue, see https://github.com/mattwarren/Ninject/commit/cc4537203e6a571a608dd13e4f95f8fb5dc6a70d

**Comment by idavis** [comment]
Hi Matt,

Can you try this:

``` cs
public class MyModule : NinjectModule
{
    public override void Load()
    {
        Kernel.Components.RemoveAll<ISelector>();
        Kernel.Components.Add<ISelector, MySelector>();
    }
}

public class MySelector : Selector
{
    public override IEnumerable<ConstructorInfo> SelectConstructorsForInjection(Type type)
    {
       if(type.IsGeneric && type.GetGenericTypeDefinition.Name.StartsWith("Func`"))
       {
            return null;
       }
       return base.SelectConstructorsForInjection(type);
    }
}
```

Load that module into your kernel during initialization and it should bypass the IL emitting.

Can you give that a try and let me know. I can't run the code right now to test.

**Comment by mattwarren** [comment]
Thanks Ian, that's solved the problem.

I didn't realise that Ninject was that flexible, so thanks for pointing out the mechanism of wiring up Modules/Selectors.

BTW to get it to compile, I had to change `MySelector` to the following:

``` csharp
public class MySelector : Selector
{
	public MySelector(IConstructorScorer constructorScorer, IEnumerable<IInjectionHeuristic> injectionHeuristics)
		: base(constructorScorer, injectionHeuristics)
	{
	}

	public override IEnumerable<ConstructorInfo> SelectConstructorsForInjection(Type type)
	{
		if (type.IsGenericType && type.GetGenericTypeDefinition().Name.StartsWith("Func`"))
		{
			return null;
		}
		return base.SelectConstructorsForInjection(type);
	}
}
```

I had to add the 2 param constructor and and changed parts of the `if (..)` statement, I assume these are the correct changes?

**Comment by idavis** [comment]
You are most likely correct. I just typed that module code from memory. You can replace virtually all components that Ninject uses internally in order to customize the behavior you want in the system.

If you are ever up for it, take a look at a few of the extensions and you'll see that they use these kind of extension points in order to add their functionality.

**Comment by mattwarren** [comment]
Ian,

Would you be willing to release a new version of Ninject with this fix included by default? It's just that our customers are reluctant to make source code changes to fix this problem?

The main issue is that their application works without our monitoring Agent, but once it's attached it triggers this issue (InvalidProgramException) within Ninject. So they see that it's our Agent that breaks things and are therefore reluctant to change their code to fix it. If we could point them to a newer version of Ninject that would be preferable, is that possible?

**Comment by scott-xu** [comment]
@mattwarren @idavis 
Could you please try https://github.com/ninject/Ninject/pull/179

**Comment by mattwarren** [comment]
@scott-xu thank's for that. I've tried it out in a few tests and it look good. I'll report back here if I find any problems.

(I did always wonder why Ninject was creating a [ConstructorInjector](https://github.com/ninject/Ninject/blob/master/src/Ninject/Injection/ConstructorInjector.cs) for a `Func/delegate`. From your fix it seems like it's not actually needed, which makes sense)

**Comment by scott-xu** [comment]
I think it was not considered for this case

**Comment by mattwarren** [comment]
When will #179 be included in an official build, so that we can download a version of Ninject.dll with it included?

**Comment by mattwarren** [comment]
Sorry if this is a dumb question, but where can I get the pre-build binaries of #179, or do you not publish those?

The latest NuGet package I can see if from [Sunday, January 04 2015](https://www.nuget.org/packages/Ninject/3.2.3-unstable-012)

**Comment by BrunoJuchli** [comment]
probably here: https://teamcity.bbv.ch/viewType.html?buildTypeId=bt7&tab=buildTypeHistoryList&branch_Ninject=%3Cdefault%3E

(use guest login)

**Comment by chris-gh** [comment]
Just seconding Matt's request for a new build with the fix implemented.
