### ISSUE TITLE
CoreCLR support in Ninject

### ISSUE THREAD

**Issue by sergey-litvinov** [ninject/Ninject#185]
Hey guys,

We have one web application that uses Ninject as DI container, and we have some plans to support CoreCLR subset. But Ninject currently doesn't support CoreCLR and DNX. Do you have any plans for supporting it? Or if someone makes this support, would you agree to merge it after review?

**Comment by scott-xu** [comment]
Agree to merge if someone makes it support

**Comment by jeremymeng** [comment]
@onovotny already added https://github.com/ninject/Ninject/blob/master/Portable.Ninject.nuspec. Maybe it is just as easy as adding the PCL output to the 'dotnet' folder, and add its dependency group.  Or does it need to be an output from Profile 259 PCL project?

**Comment by onovotny** [comment]
It's more than that presently. The PCL portion is really a façade, a reference assembly. It still needs a compiled version; this should be do-able with a "modern PCL" that targets Win10, ASPNet5 and Net46 but it's a matter of time.

**Comment by jeremymeng** [comment]
Let me give it a try.

**Comment by mwhelan** [comment]
Just wondering how this is going? Is .Net Core support coming for Ninject?

**Comment by scott-xu** [comment]
I just ported version 3.2 to .net core: https://github.com/scott-xu/Ninject

**Comment by mwhelan** [comment]
Hi @scott-xu. Is it available on NuGet, or what is the best way to get hold of it?

**Comment by scott-xu** [comment]
Not yet

发自我的 iPhone

**Comment by scott-xu** [comment]
Pushed to Nuget

**Comment by jeremymeng** [comment]
@scott-xu Thanks for the work to support .NET Standard.  Do you know when the package will be out of Beta?
