### ISSUE TITLE
How to Inject new DbContext to every repository in every request

### ISSUE THREAD

**Issue by eminyuce** [ninject/Ninject#191]
I am using EF 6 and Repository Pattern with Ninject DI. I need to create a new DbContext for every repository  in the request scope. Each repository must use different DbContext in order to get data from EF 6 async method.

How can I create a new context for each my repository in the request scope in Ninject DI? I am using EF 6 and repository pattern and I need to create new DbContext for each my repository ? I think the below approach is not working because repositories are disposing dbContext after EF 6 async method call.

                kernel.Bind<IContentService>().To<ContentRepository>().InRequestScope().WithConstructorArgument("dbContext", new StoreContext(AppConstants.ConnectionStringName));
                kernel.Bind<IStoreService>().To<StoreRepository>().InRequestScope().WithConstructorArgument("dbContext", new StoreContext(AppConstants.ConnectionStringName));
                kernel.Bind<ISettingService>().To<SettingRepository>().InRequestScope().WithConstructorArgument("dbContext", new StoreContext(AppConstants.ConnectionStringName));

**Comment by retailcoder** [comment]
IMO you're doing it wrong: "I need to create a new DbContext for every repository" sounds completely wrong, as does "I am using EF 6 and Repository Pattern" - EF *is* a unit-of-work / repository pattern, you're wrapping an abstraction with... an abstraction.

Relevant:
 - [Correct usage of EF's DBContext in ASP.NET MVC application with Castle Windsor](http://codereview.stackexchange.com/a/35653/23788)
 - [EF Generic Repository + Unit of Work pattern with support for Async](http://codereview.stackexchange.com/a/104093/23788)

**Comment by eminyuce** [comment]
Let me tell you why I did it. I am using GenericRepository with EF6 to get data. Generic Repository manages query inside repository.. The project I used as generic repository.

http://www.tugberkugurlu.com/archive/clean-better-and-sexier-generic-repository-implementation-for-entity-framework

 The web application I worked is not using Repository directly to fetch data, it is using service interfaces. The service interfaces has two different impelementations, one is repositories and other is web json api implementation. It is working fine with web json api implementation which is just getting data from HTTP request. But then I realized my repository is not working because they have to have different DBContext to manage async methods

http://stackoverflow.com/questions/29763732/entity-framework-async-issues-context-or-query#new-answer

**Comment by eminyuce** [comment]
To explain the issue further, I tried to create my services without ninject DI like the below code and it works because DbContext is created in every request.


            IProductService rep = new ProductRepository(new StoreContext(ConnectionString));
            IContentService rep2 = new ContentRepository(new StoreContext(ConnectionString));
            IPageDesignService rep3 = new PageDesignRepository(new StoreContext(ConnectionString));
            IProductCategoryService rep4 = new ProductCategoryRepository(new StoreContext(ConnectionString));
            ICategoryService rep5 = new CategoryRepository(new StoreContext(ConnectionString));
            IFileManagerService rep6 = new FileManagerRepository(new StoreContext(ConnectionString));


            var productsTask = rep.GetProductsByBrandAsync(StoreId, 5, 100, null);
            var pageDesignTask = rep3.GetPageDesignByName(StoreId, "HomePage");
            var blogsTask = rep2.GetMainPageContentsAsync(StoreId, categoryId, StoreConstants.BlogsType, 5);
            var newsTask = rep2.GetMainPageContentsAsync(StoreId, categoryId, StoreConstants.NewsType, 5);
            var productCategoriesTask = rep4.GetProductCategoriesByStoreIdAsync(StoreId, StoreConstants.ProductType, true);
            var categoriesTask = rep5.GetCategoriesByStoreIdAsync(StoreId);
            var sliderTask = rep6.GetStoreCarouselsAsync(StoreId, 58);

**Comment by eminyuce** [comment]
I did it without ninject injection. I could not find a way with ninject.
      public IContentService ContentService
        {
            get
            {
                if (ProjectAppSettings.IsApiService)
                {
                    return new ContentService(ProjectAppSettings.WebServiceAddress);
                }
                else
                {
                    return new ContentRepository(new StoreContext(AppConstants.ConnectionStringName));
                }
            }
        }

**Comment by BrunoJuchli** [comment]
This is a thing solved quite easily with a [contextual binding](https://github.com/ninject/Ninject/wiki/Contextual-Binding).

**Comment by eminyuce** [comment]
Could you give a example code?

**Comment by BrunoJuchli** [comment]
could you take 5 minutes to read the article?

**Comment by BrunoJuchli** [comment]
ok let me be a bit less mean :P

    Bind<IContentService>().To<ContentService>()
        .WithConstructorArgument("nameOfCtorArgument", ProjectAppSettings.WebServiceAddress)
        .When(ctx => ProjectAppSettings.IsApiService)
    
(maybe `WithConstructorArgument` has to come after the `When`, i'm writing this from memory)
and in the same manner for the else case.

As you can see, this results in two bindings. There's an alternative:

    Bind<IContentService>().ToMethod(ctx =>
        {
            if (ProjectAppSettings.IsApiService)
            {
                return new ContentService(ProjectAppSettings.WebServiceAddress);
            }
            else
            {
                return new ContentRepository(new StoreContext(AppConstants.ConnectionStringName));
            }
         });

**Comment by eminyuce** [comment]
Thank you so much, I used your alternative solution, I am so newbie about Ninject and using it in my first time in my project right now. It is working fine.  I think alternative solution you proposed is much more readable so I used it.
