### ISSUE TITLE
Advantage of Injecting HttpContext and HttpContextBase

### ISSUE THREAD

**Issue by eminyuce** [ninject/Ninject#193]
What is the advantage of injecting  HttpContext and HttpContextBase? How will I use them?

kernel.Bind<HttpContext>().ToMethod(ctx => HttpContext.Current).InRequestScope();
kernel.Bind<HttpContextBase>().ToMethod(ctx => new HttpContextWrapper(HttpContext.Current)).InRequestScope();

**Comment by BrunoJuchli** [comment]
This is not a discussion forum! This is an issue tracker where you report bugs and post feature requests.

Post Your questions somewhere else, for example a discussion board, mailing list or https://www.quora.com/
