### ISSUE TITLE
InRequestScope not working correctly in webforms

### ISSUE THREAD

**Issue by lukemcgregor** [ninject/Ninject#196]
I know webforms are super old and no one really wants to be using them but I noticed InRequestScope doesn't seem to work with them anymore.

If I create a dummy disposable object and bind it .InRequestScope and then view a page which injects that object the object is not disposed until the application stops (at which point the dispose method is called). This does still work correctly in MVC.

I suspect for some reason the scoping item is staying around longer than expected with webforms.

To reproduce I did the following:
- New Webforms project
- Install Ninject.Web
- Create a simple class with a dispose
- Bind it InRequestScope
- Property inject it into a page
- Load/refresh the page (this is where dispose SHOULD be getting called)
- stop the site in IIS Express (this is the point at which dispose gets called)

**Comment by lukemcgregor** [comment]
This issue doesn't occur with the latest version of Ninject.Web.Common so the fix is probably to update the Ninject.Web package to refer/prefer the newer versions

**Comment by BloodBaz** [comment]
I'm getting the same problem in now (June 2020) and I wonder if there is an issue with Ninject.Web.Common.  I've created a minimal [ASP.NET Web Form example](https://downloads.realsense-learning.co.uk/TestInRequestScopeWeb.zip) that shows the problem.

**Comment by scott-xu** [comment]
You need to install Ninject.Web. However it is outdated. I'll try update it when I have time.

**Comment by scott-xu** [comment]
Try Ninject.Web 3.3.0 please.

**Comment by BloodBaz** [comment]
I've now installed `Ninject.Web 3.3.1` that (I assume) @scott-xu updated and this now instantiates InRequestScope services once per request. Thanks.
