### ISSUE TITLE
Please release a (possibly alpha) build of the current sources

### ISSUE THREAD

**Issue by danielcweber** [ninject/Ninject#198]
Hi,

we are currently in the process of migrating our servers from a Windows environment onto a Mono-environment (running on Linux). However, #170 has prevented us from doing so with all our projects that depend on Ninject. The issue is already fixed in the sources, however, there hasn't been an update for the NuGet-package in quite a while.

Please release at least an alpha build from the current sources on NuGet. If we encounter any unknown issues in one of those builds, we will readily participate in locating and fixing them.

Thanks.

**Comment by onovotny** [comment]
I've just setup a new CI build with a MyGet CI packages feed.
https://www.myget.org/F/ninject/api/v2

Can you give that a shot? It has a build fresh from the last hour or so.

**Comment by danielcweber** [comment]
Thanks. We used to use the Factory-extension, which will not work out-of-the-box with Portable.Ninject (probably with a few binding redirects and manual csproj-editing, but that's not the point of all this). Any chance the 'official' project (with the NuGet-Id "Ninject" instead of "Portable.Ninject) will have an alpha-release ?

**Comment by onovotny** [comment]
@danielcweber I'm working on getting the main package updated. The bits in there will the same though as the portable code has merged into the main codebase. What's breaking with the portable package for you? The assembly names and identity (Strong name) are the same as the "Regular" package?

**Comment by danielcweber** [comment]
Just the fact that we would have to uninstall Ninject manually (while Ninject.Factory still depends on it) made us consider this a hack. We had to ensure the quality of our software and did not go that way.

**Comment by onovotny** [comment]
Gotcha, makes sense. I'm trying to get the main package updated but it might be a few days

**Comment by danielcweber** [comment]
Alright. Thanks a lot.
