### ISSUE TITLE
Ninject (csproj): "This project is incompatible with the current edition of Visual Studio"

### ISSUE THREAD

**Issue by brcaswell** [ninject/Ninject#199]
Are you targeting .Net Framework version or IDE versions?
I'm using Visual Studio 2013 Express...

[src/Ninject/Ninject.csproj](https://github.com/ninject/Ninject/blob/cc00946b1484db3c8d1c80c0c44e91beabc6b5be/src/Ninject/Ninject.csproj)

```
<OutputType>Library</OutputType>
<AssemblyName>Ninject</AssemblyName>
<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
<MinimumVisualStudioVersion>12.0</MinimumVisualStudioVersion>
```

I'm still reviewing this code base, but I'm not presently aware why you're targeting v4.6 (especially since the commit mention 4.5.1), and I'm certainly not aware why the minimum visual studio version is 12 (2015).

Note that visual studio 2012 and 2013 can target 4.6.
[Microsoft .NET Framework 4.6 Targeting Pack and Language Packs for Windows](https://support.microsoft.com/en-us/kb/3045566)

**Comment by onovotny** [comment]
Is there any chance you can update to the VS 2015 Community Edition? It has far more features than VS 2013 Express and is free.

What you're seeing there is a PCL profile, 151, it's not a real 4.6 target but has to do with where the PCL libraries sit on disk.
