### ISSUE TITLE
Incorrect frameworkAssembly in nuget package for Ninject.Extensions.Wcf

### ISSUE THREAD

**Issue by drieseng** [ninject/Ninject#205]
The nuget package for **Ninject.Extensions.Wcf** lists a dependency on the **System.ServiceModel.Activation** assembly.

However, this dependency only applies to the .NET 4.0 and 4.5 versions of this extension.
The nuspec actually enforces this dependency for all included .NET Framework versions.
This means that the package is not usable for .NET Framework 3.5 as that version does not even include the **System.ServiceModel.Activation** assembly.

**Comment by drieseng** [comment]
I moved (recreated) this issue in the issue tracker for **Ninject.Extensions.Wcf**.

**Comment by BrunoJuchli** [comment]
link: https://github.com/ninject/Ninject.Extensions.Wcf/issues/36
