### ISSUE TITLE
[Feature Request] Nested scopes support

### ISSUE THREAD

**Issue by AqlaSolutions** [ninject/Ninject#207]
NInject already has scopes but what if I need to have multiple layers of them?..

**Comment by BrunoJuchli** [comment]
Can you provide an example (code...) of what's _not_ working and how you expect it to work?
Currently, you can already easily nest named scopes.

**Comment by AqlaSolutions** [comment]
Yep, I've already made named scopes work in my prototype. I thought they don't support nesting because not-named custom scopes don't. But everything works now.
