### ISSUE TITLE
Binary conditional mapping to support feature toggle

### ISSUE THREAD

**Issue by andrewchaa** [ninject/Ninject#211]
Often, I instantiate two different implementations with feature toggle. For example, 

```
kernel.Bind<ILoginService>()
    .To<OAuthLoginService>().When(k => Feature.IsEnabled<OAuthAuthentication>());
kernel.Bind<ILoginService>()
    .To<LoginService>().When(k => !Feature.IsEnabled<OAuthAuthentication>());
```

I'd like to see a syntax that supports this from Ninject, something like

```
kernel.Bind<ILoginService>()
    .If(Feature.IsEnabled<OAuthAuthentication>())
    .Then<OAuthLoginService>()
    .Else<LoginService>();
```
Before I create a pull request, I'd like know you guys' opinion. What do you think?

**Comment by scott-xu** [comment]
Once we implement 'If Then Else', we need to implement 'Switch Case'. It should be language feature so I think the `Bind<ILoginService>.ToMethod()` is generic enough.
