### ISSUE TITLE
Problem with WhenInjectedInto and overloaded constructors

### ISSUE THREAD

**Issue by DavidJFowler** [ninject/Ninject#216]
I have the following bindings:

``` csharp
            var kernel = new StandardKernel();
            kernel.Bind<IThing1>().To<Thing1>().WhenInjectedInto<Item2>();
            kernel.Bind<IThing2>().To<Thing2>();
```

class Item1 has 2 constructors:

``` csharp
        // constructor 1
        public Item1(IThing1 thing1)
        {

        }

        // constructor 2
        public Item1(IThing2 thing2)
        {

        }
```

clas Item2 has a single constructor:

``` csharp
        public Item2(IThing1 thing1)
        {

        }
```

I can instantiate Item2 successfully:

``` csharp
var item2 = kernel.Get<Item2>();
```

but if I try to get an instance of Item1:

``` csharp
var item1 = kernel.Get<Item1>();
```

an exception is raised where I would have expected constructor 2 to be called:

Ninject.ActivationException was unhandled
  HResult=-2146233088
  Message=Error activating Item1 using implicit self-binding of Item1
Several constructors have the same priority. Please specify the constructor using ToConstructor syntax or add an Inject attribute.

Constructors:
Item1(IThing1 thing1)
Item1(IThing2 thing2)

Activation path:
  1) Request for Item1

Suggestions:
  1) Ensure that the implementation type has a public constructor.
  2) If you have implemented the Singleton pattern, use a binding with InSingletonScope() instead.

**Comment by BrunoJuchli** [comment]
You are most likely binding the interface but requesting the class.

Also notice that youur sample code is incomplete.

**Comment by BrunoJuchli** [comment]
Sorry, i spoke hastily before (didn't sleep a lot tonight). As far as i know Ninject does not take the `When` clauses into consideration when scoring for constructors (see [`StandardConstructorScorer`](https://github.com/ninject/Ninject/blob/master/src/Ninject/Selection/Heuristics/StandardConstructorScorer.cs).

You should be able to make use of the `ToConstructor` binding to circumvent the issue, also see Remo Gloors post on this feature [here](http://www.planetgeek.ch/2011/05/28/ninject-constructor-selection-preview/)  by Remo Gloor.

**Comment by scott-xu** [comment]
Duplicate with https://github.com/ninject/Ninject/issues/237
Fixed in https://github.com/ninject/Ninject/commit/4f5a384d881151583e76863ad5eefe1a0265d0bd
