### ISSUE TITLE
Injecting array of concrete classes always contains a single element

### ISSUE THREAD

**Issue by slaneyrw** [ninject/Ninject#227]
I'm converting an application from Unity to Ninject but I've hit an issue that I cannot find any doco on.

I have a class that has a constructor parameter that is an Array of a concrete class.  Unity will inject an empty array if I haven't explicitly registered named instances.

Ninject, on the other hand, will construct an instance of the concrete and give me an array with 1 element.
At the bottom of https://github.com/ninject/Ninject/wiki/Dependency-Injection-With-Ninject, it states that I should be able to inject 0..n.

Is an empty array only possible with interfaces ?

I cannot change the constructor signature, so is it possible to inject an empty array if no implementations of the concrete type are bound ?

**Comment by slaneyrw** [comment]
Thanks, I'll look at the custom IParameter route

**Comment by scott-xu** [comment]
Fixed by https://github.com/ninject/Ninject/commit/bf47cc9e81b754209791858d637096adcaa2e13e
