### ISSUE TITLE
DbContext with Ninject ADO.NET

### ISSUE THREAD

**Issue by symon01107** [ninject/Ninject#229]
I am working on a big project that 80% completed (Some features need to be implemented though).But recently we discovered that the project doesn't allow concurrent requests (I mean multiple users request to same repository). Sometime we get null referece & sometimes "Executed can not open available connection , connection state is closed" etc. Our source code is strongly restricted outside of the world. Here is some code.Let me know if there is any architectural problem, as architectural guys left company. It's using ninject 3.0. I already used InRequestScope() for all manager's repositories but no luck

```
public class DbContex
{
  //execute query , nonquery etc using adapter & datatable
}
```
//MyController
 ```
public class MyController
    {
       private readonly IMyManager_iMyManager;
       public MyController(IMyManager iMyManager){_iMyManager=iMyManager}

       public ActionResult Save()
       {
          _iMyManager.Save()
       }
   }
```
// My Manager
 ```
 public class MyManager:IMyManager
    {
      private readonly  IMyRepository _iMyRepository;
      DbContext _dbContext=new    
                DbContext("someParameter","connectionstring");

     public MyManager
       (
       IMyRepository iMyRepository, DbContext dbContext
       )                    
       {      
        _iMyRepository=iMyRepository;
        _dbContext=dbContext;
       }

  Public DataTable GetDataTable()
  {
    try
    {
      _dbContext.Open();
      _iMyRepository.GetDataTable()
    } 
    catch(Exception ex){}
    finally{_dbContext.Close()}
   }
 }
```
// here is the repository
```

Public class MyRepository:IMyRepository
    {
      public _dbContext;
      public MyRepository(DbContext dbContext)
      {
       _dbContext=dbContext;
      }

      public DataTable GetDataTable()
      { return _dbContext.ExecuteQuery()}
    }
```
Finally Here is our ninject binding

```
public class NinjectDependencyResolver()
{
   var context=new DbContext("someparameter","connectionStrin");
   kernel.Bind<IMyManager>().To<MyManager>().WithConstructorArgument("_dbContext",context);
   kernel.Bind<IMyRepository >().To<MyRepository >().WithConstructorArgument("_dbContext",context);
}
```
there can have some typo in my code as I wrote everything in so editor

**Comment by scott-xu** [comment]
Please let Ninject manage your DbContext

**Comment by symon01107** [comment]
Sorry , I could not understand what you mean.
Could you tell me how to do it?

**Comment by scott-xu** [comment]
You were creating the DbContext yourself and as I can see there's only one instance and never gets disposed.

**Comment by symon01107** [comment]
Thank you very much. I got some hope after 3 days.
So, what should I do here?

**Comment by scott-xu** [comment]
Bind DbContext in request scope

**Comment by symon01107** [comment]
My DbContext implements IDisposable. So, ninject should dispose it. Isn't it.
I already tried all my Manager & Repository as 
kernel.Bind<IMyManager>().To<MyManager>().InRequestScope().WithConstructorArgument("_dbContext",context);

But no difference in outcome.

**Comment by scott-xu** [comment]
You didn't bind DbContext

**Comment by symon01107** [comment]
I did using
kernel.Bind<DbContext>().ToSelf().InRequestScope();

**Comment by scott-xu** [comment]
Where?

**Comment by symon01107** [comment]
I did some thing like this 
 ```
public class NinjectDependencyResolver()
{
 var context=new DbContext("someparameter","connectionStrin");
   kernel.Bind<DbContext>().ToSelf().InRequestScope();
   kernel.Bind<IMyManager>().To<MyManager>().WithConstructorArgument("_dbContext",context);
   kernel.Bind<IMyRepository >().To<MyRepository >().WithConstructorArgument("_dbContext",context);
}
```

**Comment by scott-xu** [comment]
var context=new DbContext("someparameter","connectionStrin");
The above context is not managed by Ninject

**Comment by symon01107** [comment]
So, how to change this code. Any idea? Our team got stuck for 3 days. No one could solve.

**Comment by scott-xu** [comment]
public class NinjectDependencyResolver()
{
  kernel.Bind<DbContext>().ToMethod(ctx=>new DbContext("someparameter","connectionStrin")).InRequestScope();
  kernel.Bind<IMyManager>().To<MyManager>();
  kernel.Bind<IMyRepository >().To<MyRepository >();
}

**Comment by symon01107** [comment]
So, should I remove all WithConstructorArgument() from all my manager & Repository?

**Comment by symon01107** [comment]
Hi, I got error  here 
`kernel.Bind().ToMethod(ctx=>new DbContext("someparameter","connectionStrin")).InRequestScope();`
**Message: The services must contain at least on tytpe**

**Comment by symon01107** [comment]
Sorry, I worked. Let me test

**Comment by symon01107** [comment]
Hi, it seems your code works.
But there is one problem.
We open dbcontext in manager but when manager goes to repository dbContext connection state gets closed. Do you any idea? Any help would be great. As it seems we are very close to solve the problem.
Thanks.
