### ISSUE TITLE
api reference docs

### ISSUE THREAD

**Issue by ciez** [ninject/Ninject#231]
Could a link to Ninject API reference docs appear as one of the top menu items on ninject.org?

Could you please post this link here?

Thank you very much!

**Comment by ShaidK** [comment]
Hi do you mean [Ninject Wiki](http://www.ninject.org/wiki.html)

**Comment by ciez** [comment]
Hi,

Well the wiki describes the framework.

Api reference docs are impissible to find. Do they exist?

**Comment by ShaidK** [comment]
Hi, 

Well I check all the links within the Website (Google search as well) but couldn't find any to be honest. I don't think they have any by the look of it.
