### ISSUE TITLE
Like RoboGuice .injectMembers

### ISSUE THREAD

**Issue by Florismart** [ninject/Ninject#232]
Hi,
is there a way to force injection of members/methods/etc in a non-injected object?
Something similar to
```
public class MyPOCOClass{

	[Inject]
	public IMyService MyService { private get; set; }

	public MyPOCOClass()
	{
		Kernel.InjectMembers(this);
	}
}
```

I think it should be interesting.

Many Thanks

**Comment by BrunoJuchli** [comment]
There actually is. `Kernel.Inject(...)`. Also see https://stackoverflow.com/questions/9982617/what-does-kernel-injectinstance-actually-do
