### ISSUE TITLE
Checking if value is equal to DBNull in ParameterTarget to see if it has a DefaultValue is wrong on .NET Core

### ISSUE THREAD

**Issue by einari** [ninject/Ninject#235]
The HasDefaultValue implementation is not working correctly on .NET Core. 
The DBNull.Value check will in fact return true when it in fact does not have a default value. 

By flipping it from != to == - I got the right result, but not sure of the implications of that. 
Equally, the ParameterInfo coming in does in fact have a property called HasDefaultValue - wouldn't it be better to use this instead?  Or is there something that escapes me?

**Comment by scott-xu** [comment]
Fixed
