### ISSUE TITLE
Is there a compelling reason to require parameter names in ConstructorArguments?

### ISSUE THREAD

**Issue by StingyJack** [ninject/Ninject#238]
I'm not sure I understand the need names for the parameter types. Shouldn't type matching be enough to determine the most suitable overload, and the name being only a hint? 

Would there be opposition or "gotchas" to adding that?

**Comment by BrunoJuchli** [comment]
Consider:

    MyCtor(IFoo one, IFoo two)

As both parameters have the same type, matching by name is necessary.
Otherwise, personally, I prefer type matching as it's more refactor safe.

**Comment by szogun1987** [comment]
In my opinion There should be overloaded constructor that accepts index instead of name.

**Comment by kabua** [comment]
@szogun1987  are you suggesting (which I hope you are) that the order in which you create the IParameter array should dictate which constructor to match?

I.e.
```
IParameter[] params = new [] {
  new ConstructorArgument(fooOne),
  new ConstructorArgument(fooTwo)
}
```
Would then match ```MyCtor(IFoo one, IFoo two)```, and execute as ```MyCtor(fooOne, fooTwo)```

If so, than I totally agree with you!

**Comment by szogun1987** [comment]
Hi. I thought more about 
``
new ConstructorArgument(fooOne, 0), new ConstructroParameter(fooTwo, 1)
``

**Comment by BrunoJuchli** [comment]
@szogun1987 That's certainly a viable alternative but it's just as brittle as using names, actually even more so.
Named: If you change names without adapting the binding, activation will fail with an exception. I
Indexed: Changing the parameter sequence - given multiple parameters of the same type - will introduce a bug silently.

For all cases where you have distinct parameter types you should use typed injection anyway.

So, personally, i don't think there's any significant benefit in adding the indexed constructor arguments. It also brings downsides with it:

- initial effort for implementation
- adds code which needs to be maintained
- more options - more things to figure out for the user

@kabua

**Comment by szogun1987** [comment]
Please close this issue. I will re-open if I I recall why did I need indices (It was some weird case).

**Comment by StingyJack** [comment]
`Bar(IFoo foo1, IFoo foo2)`

Lists and array ordering has been guaranteed as preserved since about .net 3.0. If the ConstructorArguments are supplied in the order given, then type matching should suffice.

**Comment by BrunoJuchli** [comment]
@StingyJack
While corret, what will happen if you refactor your constructor and change the sequence of `foo1` and `foo2`?

Maybe the original implementation was `Bar(IBankAccount seller, IBankAccount buyer)` and you change it to `Bar(IBankAccoutn buyer, IBankAccount seller)`. That could possibly introduce a nasty issue.
So while technically possible to rely on the order, I'm not sure that's a wise thing to do. The order does not communicate intent.

**Comment by StingyJack** [comment]
I don't think you can protect against stupid mistakes (i cant protect me from my own), someone changing parameter ordering should be paying attention, and relatively minor testing would ferret out that kind of parameter swap issue. 

But it is implemented at your risk/comfort level, and safe is OK. I only brought it up again to re-focus this conversation to be about the original question, which you have addressed. Thanks!
