### ISSUE TITLE
Injection into private parent parent properties fails

### ISSUE THREAD

**Issue by AZWN** [ninject/Ninject#241]
When the Kernel option `InjectParentPrivateProperties` is set to `true`, properties of parent parent classes are still not injected. This leads to very unexpected results when api users want to use a subclass of the default implementation an API provides. 

I think, when the previously mentioned option is set, all parent class private properties should be injected, or there should be an option to allow for higher level injection.

A simple reproduction scenario might be as follows:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using Ninject;
using Ninject.Modules;
using NUnit.Framework;

namespace SelfInjectTest
{
    interface IA { }

    public class A : IA
    {
        [Inject]
        private string Name { get; set; }

        public string NameOperation()
        {
            return Name;
        }
    }

    class B : A { }

    class C : B { }

    public class Program
    {
        public static void Main(string[] args)
        {
            IKernel kernel = new StandardKernel(new NinjectSettings()
            {
                InjectParentPrivateProperties = true,
                InjectNonPublic = true
            });
            kernel.Bind<string>().ToConstant("Foo");

            var a = kernel.Get<A>();
            var b = kernel.Get<B>();
            var c = kernel.Get<C>();

            Assert.AreEqual("Foo", a.NameOperation()); // Passes
            Assert.AreEqual("Foo", b.NameOperation()); // Passes
            Assert.AreEqual("Foo", c.NameOperation()); // Fails, parent of parent property not injected
        }
    }
}
```

**Comment by BrunoJuchli** [comment]
I agree, however i'd vote to remove this feature from Ninject entirely (in a Ninject V4). Private-property injection is basically only limited to cases where bad code is written.

**Comment by AZWN** [comment]
I can imagine that, but are there any plans for such a new version? If that will still take some time, I think it is still worth the effort to fix this. If you are willing to accept pull requests, I can do it myself as well.

**Comment by scott-xu** [comment]
PR is welcome
