### ISSUE TITLE
How much GarbageCollectionCachePruner instances should we have in a runtime for a healthy app?

### ISSUE THREAD

**Issue by SychevIgor** [ninject/Ninject#242]
Hi,
I need an advise, how much instances of GarbageCollectionCachePruner we should have in a memory for a windows service app?

I have 244000( 244 thousands) objects in an app, and something telling me that it's not normal. 

![image](https://cloud.githubusercontent.com/assets/578954/26641725/266dadec-4634-11e7-8e63-1fde219a9696.png)
Based on my research it's a root cause of high cpu utilization, because we also have 245k timers in memory and each timer throwing event every 30 second... 
I think it's because something preventing timer from GC...

I need only an answer- how much GarbageCollectionCachePruner objects should be in an app and if we have some guides about normal number of loggers in a Ninject container(but it's optional)...

**Comment by scott-xu** [comment]
Should be only one
