### ISSUE TITLE
Break Singleton / circular dependency WithPropertyValue

### ISSUE THREAD

**Issue by wischmeier** [ninject/Ninject#244]
Hi,

I have the following phenomenon where I will get 2 instances for a Singleton dependency. This is the bit of code:

`   Bind<SingletonBreaker>().ToSelf().InSingletonScope();           
   Bind<Dependency>().ToSelf().InSingletonScope() 
       .WithPropertyValue(nameof(Dependency.DependOnSingletonBreaker), ctx => 
               ctx.Kernel.Get(typeof(SingletonBreaker)));
`

I want to explicitly specify the property, but by doing it this way, it breaks the circular dependency detection of the activation pipeline. This will instantiate two instances of SingletonBreaker. In my case I could fix it by using a Lazy<SingletonBreaker> dependency. But in general, I will not be warned (i.e. Exceptioned) when I have a circular dependency when using WithPropertyValue.

Does anyone have any tips or ideas what to do better or how to fix this? Am I using Ninject in the wrong way? I found this behaviour in v3 as well as in v4. Here is a complete example of the test case:

`using Ninject;
using Ninject.Modules;
using System;

namespace NinjectBreakSingletonWithPropertyValue
{
    class Program
    {
        static void Main(string[] args)
        {
            new BreakSingletonTest().Test();
        }
    }
    class BreakSingletonTest
    {

        public void Test()
        {
            var kernel = new StandardKernel(new SingletonBreakerModule());
            var singleton = kernel.Get<SingletonBreaker>();
        }
    }

    class SingletonBreaker
    {
        private static int instanceCount = 0;
        public SingletonBreaker(Dependency dependency)
        {
            if (instanceCount++ > 0)
                throw new Exception("SingletonBreaker: more than one instance.");
        }
    }

    class Dependency 
    {
        public SingletonBreaker DependOnSingletonBreaker { get; set; }
    }

    class SingletonBreakerModule : NinjectModule
    {
        public override void Load()
        {
            Bind<SingletonBreaker>().ToSelf().InSingletonScope();
            Bind<Dependency>().ToSelf().InSingletonScope()
                .WithPropertyValue(nameof(Dependency.DependOnSingletonBreaker), ctx => ctx.Kernel.Get(typeof(SingletonBreaker)));
        }
    }

}
`

**Comment by scott-xu** [comment]
Fixed in https://github.com/ninject/Ninject/commit/8de2b0273df05fae25d49bccaaef4e7df7a3d34a
