### ISSUE TITLE
Bind ToConstant creates new instance

### ISSUE THREAD

**Issue by agostinocinelli** [ninject/Ninject#248]
Hello,
i'm facing a problem with Bind ToConstant()
When I inject service into ViewModel with [Inject] decorator, it get the constant, but when i call Get() in ServiceLocator, it creates a new instance.
I think is a problem of the v4 beta, can anyone confirm?

**Comment by scott-xu** [comment]
Please try the latest build

发自我的 iPad

在 2017年9月21日，16:49，agostinocinelli <notifications@github.com<mailto:notifications@github.com>> 写道：


Hello,
i'm facing a problem with Bind ToConstant()
When I inject service into ViewModel, it get the constant, but when i call Get() in ServiceLocator, it creates a new instance.
I think is a problem of the v4 beta, can anyone confirm?

**Comment by agostinocinelli** [comment]
v 4.0.0-beta-0134 already installed.
Maybe it's not relevant, but some of solution's projects target .Net Standard 1.4 and some target Full Framework

**Comment by scott-xu** [comment]
Try this please: https://ci.appveyor.com/project/scott-xu/ninject/branch/master/artifacts

发自我的 iPhone

在 2017年9月21日，20:01，agostinocinelli <notifications@github.com<mailto:notifications@github.com>> 写道：


v 4.0.0-beta-0134 already installed.
Maybe it's not relevant, but some of solution's projects target .Net Standard 1.4 and some target Full Framework

**Comment by agostinocinelli** [comment]
Does not resolve :(
I tried both to replace Ninject.dll in the debug folder and install-package c:\temp\Ninject.4.0.0-beta.1.52.nupkg in the "exe" project

**Comment by scott-xu** [comment]
Please try https://www.nuget.org/packages/Ninject/3.3.0-beta1

**Comment by agostinocinelli** [comment]
Sorry for the late reply,
I migrated to .NET Standard 2.0 and installed Ninject 3.3.0
Tadaa, it works :)
