### ISSUE TITLE
NuGet dependencies, upgrade to 3.3 impossible

### ISSUE THREAD

**Issue by matteosaporiti** [ninject/Ninject#253]
What is the recommended upgrade path to 3.3 when using nuget?  
Nearly all the extensions are still at version 3.2,* and they depend on Ninject 3.2.* which means most projects using nuget are stuck with Ninject 3.2.3.
If the extensions will be updated in the near future it's not that big of a problem but in case it's not what is the suggested path, building everything ourselves? (I honestly would rather not)

**Comment by penihel** [comment]
Hummm. I did not see this before. So i opened this #255

**Comment by scott-xu** [comment]
- [x] Ninject.Extensions.ContextPreservation
- [ ] Ninject.Extensions.Conventions
- [x] Ninject.Extensions.Factory
- [x] Ninject.Extensions.Interception
- [x] Ninject.Extensions.Logging
- [x] Ninject.Extensions.NamedScope
- [ ] Ninject.Extensions.Wcf
- [x] Ninject.Extensions.MockingKernel
- [ ] Ninject.Web.Common

**Comment by IronSean** [comment]
I'm not sure how to interpret that response. Are those the packages that have been made 3.3.x compatible, with the .Web packages still on the older version?

**Comment by jsmarsch** [comment]
I am getting this error as well (Using Ninject, and Ninject.Extensions.Factory).  The only way I could upgrade was to uninstall Ninject.Extensions.Factory and then upgrade ninject, and then reinstall ninject.extensions.factory.

**Comment by jberke** [comment]
I am getting this issue as well. I am unable to upgrade because of the Ninject.Web* projects.

**Comment by scott-xu** [comment]
Most ticked extensions are in beta phase. Please try the 3.3.0 beta versions in nuget.
