### ISSUE TITLE
Ninject.Extensions.Conventions in lastest version  (3.3.1)

### ISSUE THREAD

**Issue by penihel** [ninject/Ninject#255]
The extention "Ninject.Extensions.Conventions" is not compatible with latest version. (3.3.1)

I cant update "ninject"  'cause i use it.

There is some plain to upgrade it too?

Thanks

**Comment by rawdrib** [comment]
We are running into the same issue trying to get to version 3.3.1 to use on .NET Standard 2.0

**Comment by scott-xu** [comment]
Ninject.Extensions.Conventions 3.3.0-beta1 released just now. Please note that all "NonePublic" has been renamed to "NonPublic"
