### ISSUE TITLE
Any plan to work on performance?

### ISSUE THREAD

**Issue by MatteoSp** [ninject/Ninject#258]
Ninject defines itself a "lightning-fast" injector, but the truth is it's one of the worst performing injectors (see [here](https://danielpalme.github.io/IocPerformance/) and [here](https://www.akshaysura.com/2016/08/31/ioc-container-benchmark-comparison-2016-including-microsoft-extensions-dependencyinjection/).

Is there any plan to work on performances?

**Comment by BrunoJuchli** [comment]
duplicate of #84

**Comment by MatteoSp** [comment]
Yes, I close it.
