### ISSUE TITLE
Resolving on a named binding

### ISSUE THREAD

**Issue by InlineAsm** [ninject/Ninject#261]
When an interface is bound to a class (named) and that class needs the same interface in it's constructor with a different name ninject throws complaining about a cyclic dependency.

This is different from the previous version of ninject which correcly resolved this,

example:

```
    interface IScreen
    {
        
    }

    class View1 : IScreen
    {
        private readonly IScreen _childView;

        public View1([Named("ChildView")] IScreen childView)
        {
            _childView = childView;
        }
    }

    class ChildView : IScreen
    {
        public ChildView()
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var kernel = new StandardKernel();
            kernel.Bind<IScreen>().To<View1>().Named("MainView");
            kernel.Bind<IScreen>().To<ChildView>().Named("ChildView");

            var instance = kernel.Get<IScreen>("MainView"); // <-- This throws with a cyclic dependency exception
        }
    }

```

**Comment by michaelestermann** [comment]
When we updated the ninject package in our solution, we ran exactly into this issue. We've seen, that its fixed but not yet provided on nuget. 
Could you please create a new package (3.3.4) containing this fix.

**Comment by scott-xu** [comment]
Released @michaelestermann

**Comment by michaelestermann** [comment]
Thanks for the fast feedback.  It just works now with the latest version 👍
