### ISSUE TITLE
Call kernel.Get<T> two times do not give the same result

### ISSUE THREAD

**Issue by Xebast** [ninject/Ninject#262]
Ninject Version : Current Release (Version 3.2)

In sample application below, we want to verify that multiple call to Get<Samurai> give the same result : throw Activation Exception - because we did not bind any IWeapon object - .

![image](https://user-images.githubusercontent.com/33876387/33094689-4b56f3ba-cf01-11e7-991b-df2ec1e7ad8d.png)

The first call is OK, exception is raised (visualized in Text Visualizer) :

![image](https://user-images.githubusercontent.com/33876387/33092775-6fca8d8e-cefb-11e7-9195-5655f2c8ae6f.png)

Unfortunnately, the second call does not throw exception and return an instance of Samurai.
This is  not what we expect.
We check that Context class uses Cache for Resolution :
- that stores an instance, created during the first call of Get<Samurai> (cache.Remember(this, reference)
(Cache is not cleared, even if ActivationException occurs after)
- that returns this instance during second call :

![image](https://user-images.githubusercontent.com/33876387/33092826-9695dd1a-cefb-11e7-8587-64008633aa6a.png)

This behavior is strange (same method Get<T> called twice gives different result), but maybe we are wrong in our expected result ? Or Maybe we have to modify Ninject Setting ? (We turned ActivationCacheDisabled to True, but no impact)
![image](https://user-images.githubusercontent.com/33876387/33092904-d3dd8434-cefb-11e7-9616-9e80e5e60e43.png)

Note : same behavior in pending V4 version.

Someone could help ?
Thanks.

**Comment by BrunoJuchli** [comment]
Could you provide the code for "copy & paste" so we can easily reproduce the issue?

**Comment by BrunoJuchli** [comment]
To summarize the issue:

When a Type (`Samurai`) is bound `InSingletonScope()` *and* uses property injection, and this property fails to inject, then a second call to `Get<Samurai>` will return a `Samurai` instance with uninitialized property.

The expected outcome would be to throw the same `ActivationException` (and, internally, not having cached the `Samurai` instance).

**Comment by Xebast** [comment]
You perfectly summarized the topic and the expected outcome.

Here is sample code : 
```
public void TestNotRequiredHelloWorld()
{
	string exceptionMessage = string.Empty;
	var ninjectSettings = new NinjectSettings() { AllowNullInjection = true };
	var kernel = new StandardKernel(ninjectSettings);

	//No Weapon defined in our Program
	//kernel.Bind<IWeapon>().To<Sword>().InSingletonScope();

	kernel.Bind<Samurai>().ToSelf().InSingletonScope();

	Samurai samurai1;
	try
	{
		//So that I expect to have exception during resolution
		samurai1 = kernel.Get<Samurai>();
	}
	catch (Exception e)
	{
		//Yes, I have expected activation exception
		exceptionMessage = e.Message;
	}

	//I try Again...
	//Here, NO EXCEPTION and a Samurai is retrieved with Weapon to null
	//And it is not the expected result
	Samurai samurai2 = kernel.Get<Samurai>();
}

class Samurai
{
	[Inject]
	public IWeapon Weapon { get; set; }

	public Samurai() { }
}

class Sword : IWeapon
{
	public Sword() { }

	public void Hit() { Console.WriteLine("Sword"); }
}

interface IWeapon
{
	void Hit();
}
```

**Comment by Xebast** [comment]
Hi BrunoJuchli and scott-xu,
Thank you for your quick feedback and fix !
