### ISSUE TITLE
Ninject.org build server link

### ISSUE THREAD

**Issue by jilola** [ninject/Ninject#265]
Currently the [Ninject build server](http://dmzytr01:8080/hub/api/rest/oauth2/auth?access_type=online&scope=0-0-0-0-0+39f9e3eb-823b-455b-8c1e-d4195b9feb4e&response_type=code&redirect_uri=https%3A%2F%2Fteamcity.bbv.ch%2FhubPlugin%2Flogin.html&state=%2FviewLog.html%3FbuildTypeId%3Dbt7%26buildId%3DlastPinned%26tab%3Dartifacts&client_id=39f9e3eb-823b-455b-8c1e-d4195b9feb4e) link leads to an non-existent/unreachable site.

**Comment by scott-xu** [comment]
It has been migrated to [appveyor](https://ci.appveyor.com/project/Ninject/ninject/ninject)
