### ISSUE TITLE
Thread blocking issue on high traffic site

### ISSUE THREAD

**Issue by cblaze22** [ninject/Ninject#268]
We just started our peak season and our traffic is causing some performance issues.  We used LeanSentry to try to diagnose the issue, and the techs over their said that something in Ninject is blocking threads.  Below you will find the screenshots they sent and they also said quote "We've seen a number of issues with Ninject and circular dependencies/deadlocks, you may get some info by poking around online.".

We are currently using 3.2.2.0 version.

![clipboard-a4451e29](https://user-images.githubusercontent.com/556494/38965521-51dab5dc-434b-11e8-9c06-9c59299ad3f9.png)

![clipboard-a22e7427](https://user-images.githubusercontent.com/556494/38965523-5451b43c-434b-11e8-83e4-026669f43a6f.png)

**Comment by BrunoJuchli** [comment]
When cross posting please mention that you do so and link to cross posts.

**Comment by cblaze22** [comment]
You mean like with Stackoverflow or something?

**Comment by cblaze22** [comment]
Guys I am sorry but I switched to SimpleInjector and the problem is resolved.  I am also under 10% CPU all day.

**Comment by JustinBerger** [comment]
We are experiencing this same issue on 3.3.4.
![image](https://user-images.githubusercontent.com/19935354/43349107-bf48d5a0-91ba-11e8-8a54-bafb5974e04f.png)
It's not happening on every request, but we have ones ranging from 30 seconds to 300 seconds.

**Comment by cblaze22** [comment]
Havent had a problem since I switched to SimpleInjector. Been under 10% CPU the whole time.

**Comment by scott-xu** [comment]
Would you please try the latest build? https://ci.appveyor.com/project/Ninject/ninject/build/artifacts

**Comment by drieseng** [comment]
The next beta features a lot of performance improvements (such as [#327](https://github.com/ninject/Ninject/pull/327), which specifically improves performance of `ICache.TryGet(...)`).

Please reopen this issue if you can still reproduce this problem.
