### ISSUE TITLE
nuget package not compatible with UWP (16299) using .NET Native tool chain

### ISSUE THREAD

**Issue by hesourman** [ninject/Ninject#271]
I have a Universal Windows Platform (UWP) app targeting the Falls creators update (16299) and above so that I can use .net Standard 2.0 assemblies. NInject 3.3.4 is installed via nuget package.
NInject works perfectly in debug and release builds.
For submission to the Windows Store I have to create a build that uses the .NET Native tool chain. Enabling this setting causes the application to crash when resolving dependencies.

Using the NInject setting UseReflectionBasedInjection did not solve the issue.

Having forked the code to investigate I discovered that PropertyReflectionStrategy (and possibly MethodReflectionStrategy) require a type that does not appear to be available when I compile my app using .NET Native tool chain.

I am experimenting with removing these strategies via two additional settings. This seems to work. I am currently attempting to test this in a build that is currently being certified for the Windows Store.

My changes can be seen here
https://github.com/hesourman/Ninject/commit/33e90357d513e5aa6fa778b7740741231c489382

**Comment by scott-xu** [comment]
Thanks for reporting this!

**Comment by hesourman** [comment]
I have not tested whether changes to the Runtime Directives file (https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference) may effect the behaviour I observed. There are attributes that can be applied via this file that suggest they may merit investigation as a workaround/fix on a per-application basis.

**Comment by scott-xu** [comment]
Can you please share the error details？

**Comment by hesourman** [comment]
During a build the following warnings appear in the output

<SNIP>\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DynamicMethodInjectorFactory.Create(ConstructorInfo)' will always throw an exception due to the missing method 'DynamicMethod..ctor(string, Type, Type[], bool)' in assembly 'System.Reflection.Emit.Lightweight'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
<SNIP>\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DynamicMethodInjectorFactory.Create(PropertyInfo)' will always throw an exception due to the missing method 'DynamicMethod..ctor(string, Type, Type[], bool)' in assembly 'System.Reflection.Emit.Lightweight'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
<SNIP>\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DynamicMethodInjectorFactory.Create(MethodInfo)' will always throw an exception due to the missing method 'DynamicMethod..ctor(string, Type, Type[], bool)' in assembly 'System.Reflection.Emit.Lightweight'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
<SNIP>\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DynamicMethodInjectorFactory.EmitLoadMethodArguments(ILGenerator, MethodBase)' will always throw an exception due to the missing method 'ILGenerator.Emit(OpCode)' in assembly 'System.Reflection.Emit.ILGeneration'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
<SNIP>\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DynamicMethodInjectorFactory.EmitMethodCall(ILGenerator, MethodInfo)' will always throw an exception due to the missing method 'ILGenerator.Emit(OpCode, MethodInfo)' in assembly 'System.Reflection.Emit.ILGeneration'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
<SNIP>\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DynamicMethodInjectorFactory.EmitUnboxOrCast(ILGenerator, Type)' will always throw an exception due to the missing method 'ILGenerator.Emit(OpCode, Type)' in assembly 'System.Reflection.Emit.ILGeneration'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

**Comment by hesourman** [comment]
Attempting to resolve a type the following exception is raised

System.MissingMethodException
  HResult=0x80131513
  Message=Method 'DynamicMethod..ctor(string, Type, Type[], bool)' from assembly 'System.Reflection.Emit.Lightweight' was not included in compilation, but was referenced in DynamicMethodInjectorFactory.Create(ConstructorInfo). There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>


This exception can be worked around by setting the 'UseReflectionBasedInjection' setting of NInject to 'true'

**Comment by hesourman** [comment]
If 'UseReflectionBasedInjection' setting of NInject is set to 'true', the following method
ExtensionsForMemberInfo.ParentDefinitionMethodInfo

encounters an ArgumentNullException in the code snippet

var runtimeAssemblyInfoType = typeof(MethodInfo).Assembly.GetType("System.Reflection.RuntimeMethodInfo");
                    parentDefinitionMethodInfo = runtimeAssemblyInfoType.GetMethod("GetParentDefinition", Flags);

This is due to 'runtimeAssemblyInfoType' being null.

**Comment by scott-xu** [comment]
Try this please https://ci.appveyor.com/api/buildjobs/540od47pnnym3kd2/artifacts/src%2FNinject%2Fbin%2FRelease%2FNinject.4.0.0-alpha073.nupkg

**Comment by hesourman** [comment]
With this package, using NinjectSettings.UseReflectionBasedInjection = true the application runs.

My application does not rely on method/property injection, so I have not tested if that actually works.

**Comment by scott-xu** [comment]
@hesourman Try https://ci.appveyor.com/api/buildjobs/8m3chce94wk92mj8/artifacts/src%2FNinject%2Fbin%2FRelease%2FNinject.4.0.0-alpha078.nupkg please.
I just replace LCG with Expression build system which makes Ninject not depend on System.Reflection.Emit.ILGeneration and System.Reflection.Emit.Lightweight

**Comment by hesourman** [comment]
With this package (alpha078), using NinjectSettings.UseReflectionBasedInjection = false the application runs.

**Comment by drieseng** [comment]
@hesourman Thanks for the feedback. We'll soon release a new beta.

**Comment by MitchBomcanhao** [comment]
@hesourman I'm running into the same issue. What did you end up doing to get your UWP package ready to be distributed via the windows store?

@drieseng @scott-xu  I can see there was a bit of activity towards a new ninject version that would have changes for UWP but that seems to have stopped a few months ago. Any info you can share regarding UWP support?

**Comment by hesourman** [comment]
@MitchBomcanhao there were two classes that weren't supported at runtime. they were for property and method injection. Is I either didn't use them, or could trivially change my code to not use them, I added a flag to allow skipping the troublesome code.
https://github.com/hesourman/Ninject/commits/uwp16299nativetoolchain

**Comment by MitchBomcanhao** [comment]
In the end we've decided to abandon ninject as the workarounds were riskier and involved more effort than just switching to another solution.
