### ISSUE TITLE
Re-evaluate Parameters changes

### ISSUE THREAD

**Issue by drieseng** [ninject/Ninject#289]
I'm not convinced 88f31abb3aad74bbdba991a91bb3d0ea658a0e6a will actually improve performance, and whether it is the best approach.

Changing it to **IEnumerable** will prevent future optimizations that I had planned. Let's do some benchmarking for this, and consider an approach.

**Comment by scott-xu** [comment]
Just defer materialize

**Comment by drieseng** [comment]
I know, but **IEnumerable** itself isn't cheap, and since you'll need to access Parameters anyway (and even multiple times) you'll just postpone it and make it slower when you actually use it.

I'll run some benchmarks on this later (this week).

**Comment by drieseng** [comment]
Revised in #334.
