### ISSUE TITLE
Use AssemblyLoadContext for isolation

### ISSUE THREAD

**Issue by drieseng** [ninject/Ninject#295]
We should consider producing a .NET Core 2 assembly.
We can refactor **AssemblyNameRetriever** to use **AssemblyLoadContext** to load assemblies in isolation when this is supported by the target framework.

**Comment by scott-xu** [comment]
Assembly Scanning is to scan assemblies and load Ninject Modules automatically. It is typically used for auto load Ninject extensions.

**Comment by scott-xu** [comment]
BTW, we can use `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in ninject extensions' unit test project to resolve issue about loading assemblies from nuget packages.
