### ISSUE TITLE
Initialize Flags in ctor of Selector?

### ISSUE THREAD

**Issue by drieseng** [ninject/Ninject#296]
Can we initialize the **Flags** property in the ctor of **Selector**?
Do we want/need to take into account that the **InjectNonPublic** setting may have changed since the kernel was created?

**Comment by scott-xu** [comment]
I'd prefer sunset `InjectNonPublic`. In my opinion, this behavior is not the best practice. Non public is designed to not be changed externally. Thoughts?

**Comment by drieseng** [comment]
I totally agree!

**Comment by drieseng** [comment]
I've created issue #297  to remove private property injection.
