### ISSUE TITLE
Bind/Rebind to a constant generic List always returns an empty list

### ISSUE THREAD

**Issue by pcroc** [ninject/Ninject#333]
```
StandardKernel kernel = new StandardKernel();

List<int> list = new List<int> { 1, 2, 3, 4, 5 };
kernel.Bind<List<int>>().ToConstant(list).InSingletonScope();

var result = kernel.Get<List<int>>();

Console.WriteLine("{0}", list.Count); // 5
Console.WriteLine("{0}", result.Count); // 0, expected 5
Console.WriteLine("{0}", result == list); // False, expected True
```

Ninject version 3.3.4

**Comment by drieseng** [comment]
This can be easily fixed (for 4.x or 5.x), but I'll need to discuss this with @scott-xu.

**Comment by JaronPiet** [comment]
Run into this issue too.

**Comment by drieseng** [comment]
@pcroc @JaronPiet This is now fixed in **master**. As an added bonus you'll get some serious performance gains.

**Comment by Sreini** [comment]
Is there any way I can get this in my own project? The last ninject release is really old at this point and I need this fix as I had the same issue.
