### ISSUE TITLE
Ninject.Web.Common.WebHost 3.3.1 "type or namespace name...not found" NinjectHttpModule OnePerRequestHttpModule

### ISSUE THREAD

**Issue by ericcbohn** [ninject/Ninject#354]
I'm getting the following errors after upgrading Ninject.Web.Common.WebHost to 3.3.1 from 3.3.0.  When downgrading back to 3.3.0 it resolves.

The type or namespace name 'NinjectHttpModule' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'OnePerRequestHttpModule' could not be found (are you missing a using directive or an assembly reference?)

**Comment by scott-xu** [comment]
Please make sure all depdenecies are up to date
