### ISSUE TITLE
Defining Ninject's binding without scope to keep the code DRY

### ISSUE THREAD

**Issue by HoomanBahreini** [ninject/Ninject#372]
This is a question (not a bug)... I have a web project and a windows service in my solution. I have created 2 different binding modules for these 2 projects, but as you can see it has a lot of duplicate code... the only difference is that I am using InRequestScope() for Web Project and InTransientScope() for Windows Service project.

Is it possible combine the bindings, and add the scope depending on the project/entry point?

````
public class WebModule : NinjectModule
{
    public override void Load()
    {
        Bind<ApplicationDbContext>().ToSelf().InRequestScope();
        Bind<IMyRepository>().To<MyRepository>().InRequestScope();
        // more types... InRequetScope();
    }
}

public class ServiceModule : NinjectModule
{
    public override void Load()
    {
        Bind<ApplicationDbContext>().ToSelf().InTransientScope();
        Bind<IMyRepository>().To<MyRepository>().InTransientScope();
        // more types... InTransientScope();
    }
}
````

**Comment by scott-xu** [comment]
You can use InRequestScope for both

**Comment by HoomanBahreini** [comment]
@scott-xu : thanks for this, would you be able to add an explanation please? I am confused as there is no request in service, so what would happen if I use InRequestScope in a service? Thanks in advance.

**Comment by scott-xu** [comment]
It will look for all `INinjectHttpApplicationPlugin`s and call `GetRequestScope`. For web applications, the `GetRequestScope` returns `HttpContext.Current` which in your windows service is null. null scope means transient scope.

**Comment by HoomanBahreini** [comment]
Thank a lot
