### ISSUE TITLE
Ninject InRequestScope disposes objects before request gets completed

### ISSUE THREAD

**Issue by hiteshnsharma** [ninject/Ninject#373]
I am running Ninject 2.2 in my web application. I have an object which holds DBContext. I bind this objects such that

```
kernel.Bind<IMyUow>().To<MyUow>().InRequestScope();
```
MyUow class implements IDisposable. What I am noticing is the Dispose method gets called while there are still so much operations to be performed. My DBContext still has to perform certain operations and queries, or in some cases, Enumerator of the Entity Query. 
I am not getting why Dispose getting called even before my operations are completed.

**Comment by corrupt-code** [comment]
I have updated Ninject to the latest 3.3.4 and yet I can see this error.

**Comment by scott-xu** [comment]
Can you please share a sample application?
