### ISSUE TITLE
NinjectControllerFactory.GetControllerInstance (RequestContext, Type) no suitable method found to override

### ISSUE THREAD

**Issue by henimex** [ninject/Ninject#383]
hi i'm trying to continue an old education but it fails under this one with 
**NinjectControllerFactory.GetControllerInstance (RequestContext, Type) no suitable method found to override**
I was downloaded the teacher's file it's ok there is no error but I'm getting that one
```
using System;
using System.Web.Mvc;
using System.Web.Routing;
using Ninject;
using Ninject.Modules;


namespace HenDevFramework.Core.Utilities.Mvc.Infrastructure
{
    public class NinjectControllerFactory:DefaultControllerFactory
    {
        private IKernel _kernel;

        public NinjectControllerFactory(INinjectModule module)
        {
            _kernel = new StandardKernel(module);
        }

        protected override IController GetControllerInstance(RequestContext requestContext, Type controllerType)
        {
            return controllerType == null ? null : (IController) _kernel.Get(controllerType);
        }
    }
}

```

**Comment by scott-xu** [comment]
Which version of ASP.NET MVC are you using? Is the `DefaultControllerFactory` from older ASP.NET MVC？

**Comment by henimex** [comment]
Assembly: System.Web.Mvc, Version=2.0.0.0
i just noticed that teachers file is
System.Web.Mvc, Version=5.2.3.0

how could i change my mvc version

**Comment by scott-xu** [comment]
use nuget please

**Comment by henimex** [comment]
really sorry for all trouble i fixed the issue with Install-Package Microsoft.AspNet.Mvc -Version 5.2.3 thank you for your time

**Comment by scott-xu** [comment]
u r welcome
