### ISSUE TITLE
Dependency with a default (null) argument result in InvalidProgramException when targeting net6.0

### ISSUE THREAD

**Issue by WGroenestein** [ninject/Ninject#386]
When you have a dependency with a default (null) argument and have null injection enabled on the kernel, when targeting net6.0, it will throw an InvalidProgramException (Common Language Runtime detected an invalid program). On net5.0 it succeeds happily.

An example of a dependency with the scenario:
```cs
class ClassWithOptionalArgument
{
	public ClassWithOptionalArgument(string keyPrefix = null)
	{
		Console.WriteLine(keyPrefix);
	}
}
```

A full repro can be found here: [Repro repo](https://github.com/WGroenestein/NinjectNet6DefaultArgumentBug)

**Comment by scott-xu** [comment]
Thanks for reporting the issue. The bug is fixed. You can try it out from CI build: https://ci.appveyor.com/project/Ninject/ninject/builds/43200302/artifacts
