### ISSUE TITLE
newVersion="3.2.0.0"

### ISSUE THREAD

**Issue by smarteez17** [ninject/Ninject#396]
Hi there. Please can I get some help. I have version 3.2.0.0 in a prod env and as of this morning it stopped working. 

<bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />

{"message":"An error has occurred.","exceptionMessage":"An error occurred when trying to create a controller of type 'CompositeItemsController'. Make sure that the controller has a parameterless public constructor.","exceptionType":"System.InvalidOperationException","stackTrace":"   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","innerException":{"message":"An error has occurred.","exceptionMessage":"Object reference not set to an instance of an object.","exceptionType":"System.NullReferenceException","stackTrace":"   at WS_COMPITEMS.ContextProvider.CreateInstance(IContext context)\r\n   at Ninject.Activation.Provider`1.Create(IContext context)\r\n   at Ninject.Activation.Context.ResolveInternal(Object scope)\r\n   at Ninject.Activation.Context.Resolve()\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)\r\n   at Ninject.Activation.Context.ResolveInternal(Object scope)\r\n   at Ninject.Activation.Context.Resolve()\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)\r\n   at Ninject.Activation.Context.ResolveInternal(Object scope)\r\n   at Ninject.Activation.Context.Resolve()\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at Ninject.ResolutionExtensions.TryGet[T](IEnumerable`1 iterator)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)"}}

**Comment by scott-xu** [comment]
Can you please share the implementation of `WS_COMPITEMS.ContextProvider.CreateInstance`

**Comment by smarteez17** [comment]
using WS_COMPITEMS.DAL;
using Ninject.Activation;
using System.Web;

 

namespace WS_COMPITEMS
{
    public class ContextProvider : Provider<PromotionItemsContext>
    { 
        protected override PromotionItemsContext CreateInstance(IContext context)
        {
            HttpContext ctx = HttpContext.Current;
            string dc = ctx.Request.Cookies["dcShortCode"].Value;
            string connStr = "";

 

            switch (dc.ToUpper())
            {
                case "KZN":
                    connStr = "KZN_PromoItemDb";
                    break;          
                case "EST":         
                    connStr = "EST_PromoItemDb";
                    break;         
                case "CPT":        
                    connStr = "CPT_PromoItemDb";
                    break;          
                case "LVD":         
                    connStr = "LVD_PromoItemDb";
                    break;          
                case "NTH":         
                    connStr = "NTH_PromoItemDb";
                    break;          
                case "STH":         
                    connStr = "STH_PromoItemDb";
                    break;
                default:
                    connStr = "CO_PromoItemDb";
                    break;
            }

            PromotionItemsContext promoDbContext = new PromotionItemsContext(connStr);

 

            return promoDbContext;
        }
    }
}

**Comment by scott-xu** [comment]
What if dc is Null?

**Comment by smarteez17** [comment]
Hi @scott-xu  DC is never null as the user dc come from AD and a dropdown . This app has been working for years and as of this monring we getting this error
