### ISSUE TITLE
How to use Ninject.Extensions.Conventions in Ninject 3.3.6?

### ISSUE THREAD

**Issue by santutu** [ninject/Ninject#400]
Does ninject  have built-in  conventions based binding?  like named scope or factory.
Ninject.Extensions.Conventions does not support ninject 3.3.6.

**Comment by lsoft** [comment]
@santutu too late perhaps 😁 but we are using

```
    <PackageVersion Include="Ninject" Version="3.3.6" />
    <PackageVersion Include="Ninject.Extensions.Conventions" Version="3.3.0" />
```

without any troubles!
