### ISSUE TITLE
Please remove pdb files from Nuget packages

### ISSUE THREAD

**Issue by j2jensen** [ninject/Ninject#62]
Having the .pdb files included in Ninject's NuGet packages causes Visual Studio to think that Ninject should be included in "Just My Code." This causes the issues mentioned [here](http://stackoverflow.com/questions/9029736/no-source-available-when-debuggin-ninject), [here](http://stackoverflow.com/questions/9029736/no-source-available-when-debuggin-ninject), and [here](http://stackoverflow.com/questions/7048585/restrict-visual-studio-2010-from-debugging-third-party-dll-files). Looking at other popular NuGet modules (Elmah, HttpModuleMagic, WebActivator, Microsoft.Web.Infrastructure, etc.), it appears that the standard convention is to not include the .pdb files. 

You can set up nuget to push a special "symbols" version to symbolsource.org as described [here](http://lostechies.com/joshuaflanagan/2011/06/23/tips-for-building-nuget-packages/), so that if users would like to step into Ninject code, they can configure Visual Studio to pull both the .pdb and the source files from symbolsource.org. So there should be no reason to include these files in the standard Nuget package on nuget.org.

**Comment by mc0re** [comment]
I'd very much like the PDB file for Ninject - where can I find it now, that it's not a part of NuGet??
